title: Startseite


columns:
  - width: 2/3
    sections:
      # all images displayed as nice cards
      images:
        headline: Images
        type: files
        query: page.images
        layout: cards


  - width: 1/3
    sections:

      # the content for the page
      content:
        type: fields
        fields:
          cover:
            label: Cover
            type: files
            max: 1
            required: true
          text:
            label: Text
            type: textarea
          productInfo:
            label: Product Info
            type: textarea
          price:
            label: Price
            type: number
            required: true
            step: .01
            min: 0
            before: €
          tax:
            label: Tax
            type: number
            required: true
            step: 1
            min: 0
            max: 100
            after: %
          priceInfo:
            label: Price Info
            type: text
          metaDescription:
            label: Meta Description
            type: textarea
            buttons: false
